/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  algoSidebar: [{ type: 'autogenerated', dirName: 'algo' }],
  toolStackSidebar: [{ type: 'autogenerated', dirName: 'tool-stack' }],
  dotnetSidebar: [{ type: 'autogenerated', dirName: 'dotnet' }],
  patternSidebar: [
    {
      type: 'category',
      label: 'Design Pattern',
      items: [{ type: 'autogenerated', dirName: 'design-pattern' }]
    },
    {
      type: 'category',
      label: 'Architecture Pattern',
      items: [{ type: 'autogenerated', dirName: 'architecture-pattern' }]
    }],
  devOpsSidebar: [{ type: 'autogenerated', dirName: 'dev-ops' }],
  techSidebar: [
    {
      type: 'category',
      label: '.Net',
      items: [{ type: 'autogenerated', dirName: 'dotnet' }]
    },
    {
      type: 'category',
      label: 'Message Queue',
      items: [{ type: 'autogenerated', dirName: 'mq' }]
    },
    {
      type: 'category',
      label: 'OpenTelemetry',
      items: [{ type: 'autogenerated', dirName: 'open-telemetry' }]
    }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
